### ISSUE TITLE
Error in GDScriptGetDeclNamespace

### ISSUE THREAD

**Issue by p-kolacz** [clktmr/vim-gdscript3#3]
When I press `K` I got this:

```
Error detected while processing function GDScriptOpenDocumentation[10]..GDScriptGetDeclNamespace:                                                                                              
line    1:                                                                                                                                                                                     
Traceback (most recent call last):                                                                                                                                                             
Error detected while processing function GDScriptOpenDocumentation[10]..GDScriptGetDeclNamespace:                                                                                              
line    1:                                                                                                                                                                                     
  File "<string>", line 1, in <module>                                                                                                                                                         
Error detected while processing function GDScriptOpenDocumentation[10]..GDScriptGetDeclNamespace:                                                                                              
line    1:                                                                                                                                                                                     
  File "/home/piotr/.vim/plugged/vim-gdscript3/plugin/../python/init.py", line 47, in gdscript_get_decl_namespace                                                                              
Error detected while processing function GDScriptOpenDocumentation[10]..GDScriptGetDeclNamespace:                                                                                              
line    1:                                                                                                                                                                                     
    vim.command("let gdscript_decl_namespace = {}".format(str(sym_info)))                                                                                                                      
Error detected while processing function GDScriptOpenDocumentation[10]..GDScriptGetDeclNamespace:                                                                                              
line    1:                                                                                                                                                                                     
vim.error: Vim(let):E121: Undefined variable: None                                                                                                                                             
Error detected while processing function GDScriptOpenDocumentation:                                                                                                                            
line   10:                                                                                                                                                                                     
E171: Missing :endif  
```

I tried to find what this error means, but I don't know vimscript enough to do this

**Comment by clktmr** [comment]
The plugin tries to lookup the symbol and in this case failed.  I
changed the behaviour to fallback to searching the Godot docs, see
ebfa25f

**Comment by p-kolacz** [comment]
Thanks, it works now.
